### ISSUE TITLE
Existing minion keys are not overwritten even if -F is specified.

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt-bootstrap#1105]
### Description of Issue/Question

I am framing this as a query rather than a pull request, because there may have been a very
good reason why the programmer decided to do the code the way it is, rather than the way
that would be very convenient for my use case: I want to take control of an existing machine.

As salt-bootstrap is now implemented, I would have to run the deploy command twice:
once to install salt,
a second time with `-C` to configure the minion as I need.

I tried adding a `-F` to the deploy command to do it all in one pass, which does not work.

I am updating the salt-cloud "saltify" driver so that it will be capable of re-assigning a hardware
machine to a different salt-master. 

The `salt-cloud -p` command creates a new key pair for a new minion which it is creating, and sends
that key pair to the minion along with the salt-bootstrap code and a new minion config file.
It loads the minion's public key into the master's pki directory so that it will be accepted
as soon as the minion becomes active.  It then executes the salt-bootstrap script with 
a `-c /tmp/xxx` option.
Unfortunately, if salt-minion were to have been started earlier, a different key pair will
have been placed in /etc/salt/pki/minion, and those files are not replaced. 
When the minion tries to connect to its new master, the public keys are different,
and the connection is immediately rejected.

The obvious solution is to add a `-F` option to the salt-bootstrap command line. [ the command is run about line 1541 of salt/utils/cloud.py ] That solution will not work because the key pair files are
explicitly excluded from copying unless the `-C` option has been specified. 

This exclusion was applied in [#848]( https://github.com/saltstack/salt-bootstrap/pull/848) which seems to me to be slightly odd.  
That PR changed a hard-wired `BS_TRUE` value into a reference to `_CONFIG_ONLY`. 
If the `BS_TRUE` value had simply been removed, so that the value of 
`_FORCED_OVERWRITE` was used, would that not have solved #830 without disabling `-F`?

### Setup

A Virtualbox VM is running Ubuntu 16.04 which has had Salt previously installed - as would be
normal in my use case. Salt-cloud is running in a Python virtual environment on my workstation,
(since I am updating it). For our purposes, the current stable version of salt-cloud should produce
the same result.  (My added options would not work, of course.)

```
# /etc/salt/cloud.profiles.d/saltify_demo_profiles.conf

quail16:   # example machine created by "vagrant up quail16"
  ssh_host: 192.168.8.3  # hard-wired in the Vagrantfile
  ssh_username: vagrant
  password: vagrant
  provider: saltify_provider_10
  shutdown_on_destroy: true
  remove_config_on_destroy: false

quail14:   # example machine created by "vagrant up quail14"
  ssh_host: 192.168.8.4  # hard-wired in the Vagrantfile
  ssh_username: vagrant
  password: vagrant
  provider: saltify_provider_10
```
```
# /etc/salt/cloud.providers.d/saltify_provider.conf
saltify_provider_10:
  driver: saltify
  eauth: pam
  username: sdb://osenv/USER
  password: sdb://salt-cloud-keyring/password
      # The salt-api user password is stored in keyring
      # don't forget to set the password by running something like:
      # salt-call sdb.set 'sdb://salt-cloud-keyring/password <yourpassword>
```
```
# This file managed by SaltStack. Any changes may be overwritten.
# /etc/salt/master.d/api.conf

rest_cherrypy:
  host: localhost
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  thread_pool: 30
  socket_queue_size: 10
  # webhook_disable_auth: True

osenv:
  driver: env

salt-cloud-keyring:
  driver: keyring
  service: system

external_auth:
  pam:
    sudo%:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
```

### Steps to Reproduce Issue

The target system is running Salt, but it is not pointing to my server...

    # running on the anticipated cloud member
    vagrant@quail16:~$ sudo systemctl stop salt-minion
    vagrant@quail16:~$ sudo rm -r /etc/salt
    vagrant@quail16:~$ sudo systemctl start salt-minion 

Let's connect it to my master...

```
# running on the new salt-master
$ salt-cloud  -c $VIRTUAL_ENV/etc/salt -p quail16 q16
[... clip ...]
Connection to 192.168.8.3 closed.
 *  INFO: Salt installed!
[... clip ...]
q16:
    ----------
    deployed:
        True
$ salt-key  -c $VIRTUAL_ENV/etc/salt -L 
Accepted Keys:
devmin
q16
q24
vcd
Denied Keys:
q16
Unaccepted Keys:
Rejected Keys:
```

"What the devil?": my user says. "How can it be Accepted and Denied at the same time?"
"Check the status..."

```
$ sudo systemctl status salt-minion
---------
salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2017-06-21 22:33:42 GMT; 22min ago
  Process: 30012 ExecStart=/usr/bin/salt-minion (code=exited, status=0/SUCCESS)
 Main PID: 30012 (code=exited, status=0/SUCCESS)

Jun 21 22:33:27 quail16 systemd[1]: Starting The Salt Minion...
Jun 21 22:33:28 quail16 salt-minion[30012]: [INFO    ] Setting up the Salt Minion "q16"
Jun 21 22:33:28 quail16 salt-minion[30012]: [INFO    ] Starting up the Salt Minion
Jun 21 22:33:28 quail16 salt-minion[30012]: [INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_e963db004a_pull.ipc
Jun 21 22:33:28 quail16 systemd[1]: Started The Salt Minion.
Jun 21 22:33:42 quail16 salt-minion[30012]: [INFO    ] Creating minion process manager
Jun 21 22:33:42 quail16 salt-minion[30012]: [CRITICAL] The Salt Master has rejected this minion's public key!
Jun 21 22:33:42 quail16 salt-minion[30012]: To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
```

### Versions and Systems

The file loaded and executed by salt-cloud...
```
vagrant@quail16:/tmp/.saltcloud-9aebf1f8-a086-427d-a5fc-318da1e61a1a$ sh deploy.sh -v
deploy.sh -- Version 2017.05.24
```

The source I was running is from [my fork](https://github.com/vernondcole/salt/tree/fix-40962)

```
$ salt-cloud  -c $VIRTUAL_ENV/etc/salt --version
salt-cloud 2017.7.0-217-g08b08de (Nitrogen)
```
The PyCharm debugger says my command was:
`'/tmp/.saltcloud-ae1c05d2-00d4-49d1-87fa-b40644ecdae0/deploy.sh -F -c \\'/tmp/.saltcloud-ae1c05d2-00d4-49d1-87fa-b40644ecdae0\\' -K'`
The "-F" is my attempt to force the file copy.  
The "-K" is because I added `keep_tmp: true` to `master.d/api.conf`.
