### ISSUE TITLE
--help should be updated to explicitly call out salt-api options

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt-bootstrap#1158]
### Description of Issue/Question

After looking at the `boostrap-salt.sh` source, there appear to be at least four different states that `salt-api` can be in:
1. Not installed
2. Installed
3. Installed, running
4. Installed, running, and ready to re-run at boot.

It's not at all obvious from the `boostrap-salt --help` how to reach each of these states. It's also not obvious how to pass in `salt-api` configuration information.

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions and Systems
N/A

**Comment by rallytime** [comment]
@brianthelion Yes, standardizing the `salt-api` package installation has been on my list of things to do (in my head) for a long time, so thank you for filing this.

If you use the `git` option to install, that should allow you to have the `salt-api` files available as a workaround for now.

Can you tell me more about what you mean by using bootstrap to pass `salt-api` configuration information?

**Comment by brianthelion** [comment]
@rallytime `salt-api` depends on a set of configuration options. These live in the master configuration file:

```yaml
...
rest_cherrypy:
  port: $PORT
  debug: True
  ssl_crt: $ROOT_DIR/etc/pki/tls/certs/localhost.crt
  ssl_key: $ROOT_DIR/etc/pki/tls/certs/localhost.key
  api_acl:
    users:
      $USER:
        - '*'
external_auth:
  pam:
    $USER:
      - .*
      - '@runner'
...
```
These options need to be pushed via `bootstrap-salt` for `salt-api` to be in a useful state after bootstrap.

**Comment by rallytime** [comment]
@brianthelion Are you using salt-cloud to try and configure this? Or plain bootstrap?

**Comment by brianthelion** [comment]
@rallytime I'm using `salt-cloud` but the bootstrap arguments are the same either way, no?

**Comment by rallytime** [comment]
Hi @brianthelion - They're not quite the same. To pass master or minion configuration information to a VM you're creating with `salt-cloud`, you need to specify that in your profile/provider/map configuration (or whatever you're using to configure this VM via `salt-cloud`) under either the `master` or `minion` key.

There isn't anything explicitly defined in `salt-cloud` (at least that i could find easily...) that explains the `master`/`minion` salt-cloud config options, but you can see examples of it being used throughout the salt-cloud docs. For example, to use the `master` option to define master config options, you can see [these docs](https://docs.saltstack.com/en/latest/topics/cloud/misc.html#setting-up-new-salt-masters). 

There's an example of how to define a `minion` profile via salt-cloud in [these docs](https://docs.saltstack.com/en/latest/topics/cloud/qs.html#define-a-provider). This is using a provider example, but the same can apply to a profile:
```
my-ec2:
  driver: ec2
  <snipped>
  minion:
    master: saltmaster.example.com
```

Salt Cloud will automatically create a minion (or master if specified using `make_master: True`) using the default configuration files. That's why you'll see so many salt-cloud config examples use the `minion` option to set the master location as in the above example.

Does that help?
