### ISSUE TITLE
Salt-bootstrap on Amazon Linux does not have an option to specify version on Amazon Linux

### ISSUE THREAD

**Issue by devinnasar** [saltstack/salt-bootstrap#1212]
### Description of Issue/Question
I'm attempting to commission new minions without having to upgrade my infrastructure's salt version, for fear that a version upgrade will break my states. It seems that the commands available for specifying an older version with the bootstrap script do not properly work for amazon linux.

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
`salt-cloud -p QAAP-C OTQAAPVM0000 --script-args "git v2017.7.2"`

produces the following error:

```
Cannot find a valid baseurl for repo: amzn-main/latest
Could not retrieve mirrorlist http://repo.us-east-1.amazonaws.com/latest/main/mirror.list error was
12: Timeout on http://repo.us-east-1.amazonaws.com/latest/main/mirror.list: (28, 'Connection timed out after 5000 milliseconds')
 * ERROR: Failed to run install_amazon_linux_ami_deps()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/salt-e.pem -p 22 ec2-user@10.0.12.225 'sudo /tmp/.saltcloud-44489ec0-04f3-4492-8f99-b696cf249d11/deploy.sh -c '"'"'/tmp/.saltcloud-44489ec0-04f3-4492-8f99-b696cf249d11'"'"''' failed. Exit code: 1
```

It seems that the bootstrap script is trying to reach the following url: http://repo.saltstack.com/yum/amazon/latest/x86_64/2017.7.2/

however this doesn't exist. only this does:
http://repo.saltstack.com/yum/amazon/latest/x86_64/2017.7/
but in that directory, there is no artifact for 2017.7.2.  Those artifacts appear to be under

http://repo.saltstack.com/yum/amazon/latest/x86_64/archive/2017.7.2/

### Versions and Systems

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.12 (default, Sep  1 2016, 22:14:00)
   python-gnupg: 0.4.1
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.27-14.31.amzn1.x86_64
         system: Linux
        version: Not Installed

This is on AWS with the EC2 provider

**Comment by rallytime** [comment]
Hi @devinnasar - thanks for filing this issue. A couple of follow up questions:

- Can you tell me which version of the bootstrap script you're using?
- Does this also happen when you're running the bootstrap script directly on an Amazon Linux VM? (i.e. `sh bootstrap-salt.sh git v2017.7.2`)
- Can you please post your profile for `QAAP-C` (be sure to strip out any sensitive information)?

There are a couple of things going on here that I want to rule out first. Thanks!

**Comment by devinnasar** [comment]
Hello @rallytime. Thanks for responding. Here are the answers I could gather.

- I am using salt-bootstrap 2017.12.13.
- Yes this behavior happens even when calling the bootstrap script from a bare EC2 instance. Please keep in mind that I actually don't want to install it via git. I want to install it via package manager.
- profile for QAAP-C:
```
providers:
      AWS-EC2-USEAST1.conf:
        # AWS
        AWS-EC2-USEAST1:
          driver: ec2
          id: # Saltstack user access key
          key: # Salstsack user secret key
          private_key: /root/.ssh/salt-e.pem
          keyname: salt-e
          minion:
            master: xxx.yyy.zzz.000
            log_file: /tmp/salt/log/minion
          ssh_interface: private_ips
          ssh_username: ec2-user
profiles: 
     AP-C.conf:
        AP-C:
          provider: AWS-EC2-USEAST1
          image: ami-55ef662f
          size: m5.large
          location: us-east-1
          availability_zone: us-east-1c
          rename_on_destroy: True
          iam_profile: 'rolearn'
          securitygroupid: # webapp
            - sg-51c10a26
          del_root_vol_on_destroy: True
          del_all_vols_on_destroy: True
          block_device_mappings:
            - DeviceName: /dev/xvda # root partition
              Ebs.VolumeSize: 10
              Ebs.VolumeType: gp2 # SSD
            - DeviceName: /dev/sdf # logging partition
              Ebs.VolumeSize: 10
              Ebs.VolumeType: gp2
          tag: {'Netuitive': 'true','otcli:role': 'tomcat'}
          grains:
            owner_code: OT # Company
            role_code: AP # Application Server
            type_code: VM # Virtual Machine
          sync_after_install: grains
     QAAP-C.conf:
        QAAP-C:
          subnetid: subnet-2321187e # QAAP-C-01
          tag: {'Environment': 'qa', 'otcli:rds-sg': 'dev'}
          grains:
            env_code: QA # QA
          extends: AP-C
```
