### ISSUE TITLE
Bootstrap installs Debian 9 packages on Debian 10

### ISSUE THREAD

**Issue by johnkeates** [saltstack/salt-bootstrap#1374]
### Description of Issue/Question
Bootstrap installs Debian 9 packages on Debian 10 instead of the existing Debian 10 packages.

### Setup
Any Debian 10 system

### Steps to Reproduce Issue
bootstrap_salt.sh or bootstrap_salt.sh -x python3 on any Debian 10 system

### Versions and Systems
In a random vagrant vm:
```
/tmp/bootstrap_salt.sh -x python3 -P -c /tmp -F -c /tmp stable

Stdout from the command:

 *  INFO: Running version: 2019.10.03
 *  INFO: Executed by: 
 *  INFO: Command line: 'bootstrap-salt.sh -x python3 -P -c /tmp -F -c /tmp stable'
 *  INFO: Detected -x option. Using python3 to install Salt.

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.19.0-5-amd64
 *  INFO:   Distribution: Debian 10
```

**Comment by javierbertoli** [comment]
The [Debian 10 repo is now available](http://repo.saltstack.com/py3/debian/10/amd64/latest/), but the installer is setting now up a *Debian 9* repo due to #1375, getting [this message](https://github.com/saltstack/salt-bootstrap/pull/1375/files#diff-a8778033f6225c137abf05cf8d0bb113L3066) and now installing Salt fails on dependencies.

```bash
    docker:  *  INFO: Command line: '/tmp/saltbootstrap.sh -XUdfP -x python3 stable 2019.2'
...
...
    docker:  *  WARN: Debian 10 distribution detected, but stable packages requested. Trying packages from Debian 9. You may experience problems.
...
...
    docker: Hit:3 http://deb.debian.org/debian buster-updates InRelease
    docker: Get:4 https://repo.saltstack.com/py3/debian/9/amd64/2019.2 stretch InRelease [2853 B]
    docker: Get:5 https://repo.saltstack.com/py3/debian/9/amd64/2019.2 stretch/main amd64 Packages [4975 B]
    docker: Fetched 7828 B in 1s (7868 B/s)
    docker: Reading package lists...
    docker:  *  INFO: Running install_debian_stable()
    docker: Reading package lists...
    docker: Building dependency tree...
    docker: Reading state information...
    docker: Some packages could not be installed. This may mean that you have
    docker: requested an impossible situation or if you are using the unstable
    docker: distribution that some required packages have not yet been created
    docker: or been moved out of Incoming.
    docker: The following information may help to resolve the situation:
    docker:
    docker: The following packages have unmet dependencies:
    docker:  salt-minion : Depends: salt-common (= 2019.2.2+ds-1) but it is not going to be installed
    docker:  * ERROR: Failed to run install_debian_stable()!!!
```

**Comment by Ch3LL** [comment]
After the 2019.2.2 release I tested the develop bootstrap on debian 10 and it installed okay now:

` *  INFO: Salt installed!`

```
root@buster:~/salt-bootstrap# salt '*' test.versions
buster.localdomain:
    Salt Version:
               Salt: 2019.2.2
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.11
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
       python-gnupg: Not Installed
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist: debian 10.0 
             locale: UTF-8
            machine: x86_64
            release: 4.19.0-5-amd64
             system: Linux
            version: debian 10.0 
```

ping @javierbertoli are you using the latest develop bootstrap? seems to be working for me now.
