### ISSUE TITLE
-x python3 installation + Ubuntu 18.04 failing with GPG error

### ISSUE THREAD

**Issue by lsh-0** [saltstack/salt-bootstrap#1398]
### Description of Issue/Question

Salt bootstrap on a fresh Ubuntu 18.04 vagrant instance fails when running with:

    wget -O salt_bootstrap.sh https://bootstrap.saltstack.com --no-verbose
    sh salt_bootstrap.sh -x python3 -P -F -c /tmp stable 2017.7.8

`python2.7` *does* work however.

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

```
    basebox--vagrant: Bootstrap salt 2017.7.8
    basebox--vagrant: + echo 'Bootstrap salt 2017.7.8'
    basebox--vagrant: + wget -O salt_bootstrap.sh https://bootstrap.saltstack.com --no-verbose
    basebox--vagrant: 2019-12-11 05:18:36 URL:https://bootstrap.saltstack.com/ [272809/272809] -> "salt_bootstrap.sh" [1]
    basebox--vagrant: + sh salt_bootstrap.sh -x python3 -P -F -c /tmp stable 2017.7.8
    basebox--vagrant:  *  INFO: Running version: 2019.11.04
    basebox--vagrant:  *  INFO: Executed by: 
    basebox--vagrant:  *  INFO: Command line: 'salt_bootstrap.sh -x python3 -P -F -c /tmp stable 2017.7.8'
    basebox--vagrant:  *  INFO: Detected -x option. Using python3 to install Salt.
    basebox--vagrant: 
    basebox--vagrant:  *  INFO: System Information:
    basebox--vagrant:  *  INFO:   CPU:          GenuineIntel
    basebox--vagrant:  *  INFO:   CPU Arch:     x86_64
    basebox--vagrant:  *  INFO:   OS Name:      Linux
    basebox--vagrant:  *  INFO:   OS Version:   4.15.0-51-generic
    basebox--vagrant:  *  INFO:   Distribution: Ubuntu 18.04
    basebox--vagrant:  *  INFO: Installing minion
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable_deps
    basebox--vagrant:  *  INFO: Found function config_salt
    basebox--vagrant:  *  INFO: Found function preseed_master
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable_post
    basebox--vagrant:  *  INFO: Found function install_ubuntu_restart_daemons
    basebox--vagrant:  *  INFO: Found function daemons_running
    basebox--vagrant:  *  INFO: Found function install_ubuntu_check_services
    basebox--vagrant:  *  INFO: Running install_ubuntu_stable_deps()
    basebox--vagrant: Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
    basebox--vagrant: Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
    basebox--vagrant: Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    basebox--vagrant: Get:4 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [593 kB]
    basebox--vagrant: Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    basebox--vagrant: Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [817 kB]
    basebox--vagrant: Get:7 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [413 kB]
    basebox--vagrant: Get:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [194 kB]
    basebox--vagrant: Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [15.1 kB]
    basebox--vagrant: Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [4,684 B]
    basebox--vagrant: Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [626 kB]
    basebox--vagrant: Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [625 kB]
    basebox--vagrant: Get:13 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [601 kB]
    basebox--vagrant: Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [288 kB]
    basebox--vagrant: Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [24.1 kB]
    basebox--vagrant: Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [9,584 B]
    basebox--vagrant: Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [6,620 B]
    basebox--vagrant: Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,033 kB]
    basebox--vagrant: Get:19 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [209 kB]
    basebox--vagrant: Get:20 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages [4,288 B]
    basebox--vagrant: Get:21 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [6,120 B]
    basebox--vagrant: Get:22 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2,600 B]
    basebox--vagrant: Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [997 kB]
    basebox--vagrant: Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [319 kB]
    basebox--vagrant: Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages [7,484 B]
    basebox--vagrant: Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [9,284 B]
    basebox--vagrant: Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [4,508 B]
    basebox--vagrant: Get:28 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4,028 B]
    basebox--vagrant: Get:29 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [4,024 B]
    basebox--vagrant: Get:30 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1,856 B]
    basebox--vagrant: Fetched 7,072 kB in 5s (1,312 kB/s)
    basebox--vagrant: Reading package lists...
    basebox--vagrant: Reading package lists...
    basebox--vagrant: Building dependency tree...
    basebox--vagrant: 
    basebox--vagrant: Reading state information...
    basebox--vagrant: ca-certificates is already the newest version (20180409).
    basebox--vagrant: gnupg is already the newest version (2.2.4-1ubuntu1.2).
    basebox--vagrant: wget is already the newest version (1.19.4-1ubuntu2.2).
    basebox--vagrant: The following NEW packages will be installed:
    basebox--vagrant:   apt-transport-https
    basebox--vagrant: 0 upgraded, 1 newly installed, 0 to remove and 131 not upgraded.
    basebox--vagrant: Need to get 1,692 B of archives.
    basebox--vagrant: After this operation, 153 kB of additional disk space will be used.
    basebox--vagrant: Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.12 [1,692 B]
    basebox--vagrant: Fetched 1,692 B in 1s (2,464 B/s)
    basebox--vagrant: Selecting previously unselected package apt-transport-https.
    basebox--vagrant: (Reading database ... 
(Reading database ... 30%ading database ... 5%
(Reading database ... 60%ading database ... 35%
    basebox--vagrant: (Reading database ... 65%
    basebox--vagrant: (Reading database ... 70%
    basebox--vagrant: (Reading database ... 75%
    basebox--vagrant: (Reading database ... 80%
    basebox--vagrant: (Reading database ... 85%
    basebox--vagrant: (Reading database ... 90%
    basebox--vagrant: (Reading database ... 95%
(Reading database ... 42487 files and directories currently installed.)
    basebox--vagrant: Preparing to unpack .../apt-transport-https_1.6.12_all.deb ...
    basebox--vagrant: Unpacking apt-transport-https (1.6.12) ...
    basebox--vagrant: Setting up apt-transport-https (1.6.12) ...
    basebox--vagrant: Warning: apt-key output should not be parsed (stdout is not a terminal)
    basebox--vagrant: gpg: 
    basebox--vagrant: no valid OpenPGP data found.
    basebox--vagrant:  * ERROR: Failed to run install_ubuntu_stable_deps()!!!
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

```
    basebox--vagrant: + wget -O salt_bootstrap.sh https://bootstrap.saltstack.com --no-verbose
    basebox--vagrant: 2019-12-11 05:26:00 URL:https://bootstrap.saltstack.com/ [272809/272809] -> "salt_bootstrap.sh" [1]
    basebox--vagrant: + sh salt_bootstrap.sh -x python3 -D -P -F -c /vagrant/tmp stable 2017.7.8
    basebox--vagrant:  *  INFO: Running version: 2019.11.04
    basebox--vagrant:  *  INFO: Executed by: 
    basebox--vagrant:  *  INFO: Command line: 'salt_bootstrap.sh -x python3 -D -P -F -c /vagrant/tmp stable 2017.7.8'
    basebox--vagrant:  *  INFO: Detected -x option. Using python3 to install Salt.
    basebox--vagrant: 
    basebox--vagrant:  *  INFO: System Information:
    basebox--vagrant:  *  INFO:   CPU:          GenuineIntel
    basebox--vagrant:  *  INFO:   CPU Arch:     x86_64
    basebox--vagrant:  *  INFO:   OS Name:      Linux
    basebox--vagrant:  *  INFO:   OS Version:   4.15.0-51-generic
    basebox--vagrant:  *  INFO:   Distribution: Ubuntu 18.04
    basebox--vagrant:  * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    basebox--vagrant:  *  INFO: Installing minion
    basebox--vagrant:  * DEBUG: install_ubuntu_18_stable_deps not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_stable_deps not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_deps not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_deps not found....
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable_deps
    basebox--vagrant:  * DEBUG: DEPS_INSTALL_FUNC=install_ubuntu_stable_deps
    basebox--vagrant:  * DEBUG: config_ubuntu_18_stable_salt not found....
    basebox--vagrant:  * DEBUG: config_ubuntu_18_04_stable_salt not found....
    basebox--vagrant:  * DEBUG: config_ubuntu_18_salt not found....
    basebox--vagrant:  * DEBUG: config_ubuntu_18_04_salt not found....
    basebox--vagrant:  * DEBUG: config_ubuntu_stable_salt not found....
    basebox--vagrant:  * DEBUG: config_ubuntu_salt not found....
    basebox--vagrant:  *  INFO: Found function config_salt
    basebox--vagrant:  * DEBUG: CONFIG_SALT_FUNC=config_salt
    basebox--vagrant:  * DEBUG: preseed_ubuntu_18_stable_master not found....
    basebox--vagrant:  * DEBUG: preseed_ubuntu_18_04_stable_master not found....
    basebox--vagrant:  * DEBUG: preseed_ubuntu_18_master not found....
    basebox--vagrant:  * DEBUG: preseed_ubuntu_18_04_master not found....
    basebox--vagrant:  * DEBUG: preseed_ubuntu_stable_master not found....
    basebox--vagrant:  * DEBUG: preseed_ubuntu_master not found....
    basebox--vagrant:  *  INFO: Found function preseed_master
    basebox--vagrant:  * DEBUG: PRESEED_MASTER_FUNC=preseed_master
    basebox--vagrant:  * DEBUG: install_ubuntu_18_stable not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_stable not found....
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable
    basebox--vagrant:  * DEBUG: INSTALL_FUNC=install_ubuntu_stable
    basebox--vagrant:  * DEBUG: install_ubuntu_18_stable_post not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_stable_post not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_post not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_post not found....
    basebox--vagrant:  *  INFO: Found function install_ubuntu_stable_post
    basebox--vagrant:  * DEBUG: POST_INSTALL_FUNC=install_ubuntu_stable_post
    basebox--vagrant:  * DEBUG: install_ubuntu_18_stable_restart_daemons not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_stable_restart_daemons not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_restart_daemons not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_restart_daemons not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_stable_restart_daemons not found....
    basebox--vagrant:  *  INFO: Found function install_ubuntu_restart_daemons
    basebox--vagrant:  * DEBUG: STARTDAEMONS_INSTALL_FUNC=install_ubuntu_restart_daemons
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu_18_stable not found....
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu_18_04_stable not found....
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu_18 not found....
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu_18_04 not found....
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu_stable not found....
    basebox--vagrant:  * DEBUG: daemons_running_ubuntu not found....
    basebox--vagrant:  *  INFO: Found function daemons_running
    basebox--vagrant:  * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
    basebox--vagrant:  * DEBUG: install_ubuntu_18_stable_check_services not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_stable_check_services not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_check_services not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_18_04_check_services not found....
    basebox--vagrant:  * DEBUG: install_ubuntu_stable_check_services not found....
    basebox--vagrant:  *  INFO: Found function install_ubuntu_check_services
    basebox--vagrant:  * DEBUG: CHECK_SERVICES_FUNC=install_ubuntu_check_services
    basebox--vagrant:  *  INFO: Running install_ubuntu_stable_deps()
    basebox--vagrant: Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
    basebox--vagrant: Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
    basebox--vagrant: Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    basebox--vagrant: Get:4 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [413 kB]
    basebox--vagrant: Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    basebox--vagrant: Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [625 kB]
    basebox--vagrant: Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [593 kB]
    basebox--vagrant: Get:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [194 kB]
    basebox--vagrant: Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [15.1 kB]
    basebox--vagrant: Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [4,684 B]
    basebox--vagrant: Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [626 kB]
    basebox--vagrant: Get:12 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [601 kB]
    basebox--vagrant: Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [817 kB]
    basebox--vagrant: Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [209 kB]
    basebox--vagrant: Get:15 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages [4,288 B]
    basebox--vagrant: Get:16 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [6,120 B]
    basebox--vagrant: Get:17 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2,600 B]
    basebox--vagrant: Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [288 kB]
    basebox--vagrant: Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [9,584 B]
    basebox--vagrant: Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [24.1 kB]
    basebox--vagrant: Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [6,620 B]
    basebox--vagrant: Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [997 kB]
    basebox--vagrant: Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,033 kB]
    basebox--vagrant: Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [319 kB]
    basebox--vagrant: Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [9,284 B]
    basebox--vagrant: Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages [7,484 B]
    basebox--vagrant: Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [4,508 B]
    basebox--vagrant: Get:28 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4,028 B]
    basebox--vagrant: Get:29 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [4,024 B]
    basebox--vagrant: Get:30 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1,856 B]
    basebox--vagrant: Fetched 7,072 kB in 5s (1,441 kB/s)
    basebox--vagrant: Reading package lists...
    basebox--vagrant: Reading package lists...
    basebox--vagrant: Building dependency tree...
    basebox--vagrant: 
    basebox--vagrant: Reading state information...
    basebox--vagrant: ca-certificates is already the newest version (20180409).
    basebox--vagrant: gnupg is already the newest version (2.2.4-1ubuntu1.2).
    basebox--vagrant: wget is already the newest version (1.19.4-1ubuntu2.2).
    basebox--vagrant: The following NEW packages will be installed:
    basebox--vagrant:   apt-transport-https
    basebox--vagrant: 0 upgraded, 1 newly installed, 0 to remove and 131 not upgraded.
    basebox--vagrant: Need to get 1,692 B of archives.
    basebox--vagrant: After this operation, 153 kB of additional disk space will be used.
    basebox--vagrant: Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.12 [1,692 B]
    basebox--vagrant: Fetched 1,692 B in 1s (2,460 B/s)
    basebox--vagrant: Selecting previously unselected package apt-transport-https.
    basebox--vagrant: (Reading database ... 
(Reading database ... 60%ading database ... 5%
    basebox--vagrant: (Reading database ... 65%
    basebox--vagrant: (Reading database ... 70%
    basebox--vagrant: (Reading database ... 75%
    basebox--vagrant: (Reading database ... 80%
    basebox--vagrant: (Reading database ... 85%
    basebox--vagrant: (Reading database ... 90%
    basebox--vagrant: (Reading database ... 95%
(Reading database ... 42487 files and directories currently installed.)
    basebox--vagrant: Preparing to unpack .../apt-transport-https_1.6.12_all.deb ...
    basebox--vagrant: Unpacking apt-transport-https (1.6.12) ...
    basebox--vagrant: Setting up apt-transport-https (1.6.12) ...
    basebox--vagrant: Warning: apt-key output should not be parsed (stdout is not a terminal)
    basebox--vagrant: gpg: 
    basebox--vagrant: no valid OpenPGP data found.
    basebox--vagrant:  * ERROR: Failed to run install_ubuntu_stable_deps()!!!
    basebox--vagrant:  * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
    basebox--vagrant:  * DEBUG: Removing the temporary apt error file /tmp/apt_error.mTee7h
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

    basebox--vagrant: + sh salt_bootstrap.sh -v
    basebox--vagrant: salt_bootstrap.sh -- Version 2019.11.04
