### ISSUE TITLE
Windows bootstrap-salt.ps1 not compatible with 3004

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt-bootstrap#1610]
### Setup
Using a plain Win10 with no previous Salt installation.

### Steps to Reproduce Issue
- Ensure no artifacts from a previous Salt installation are present
- Install Salt 3004 using Windows `bootstrap-salt.ps1`:
  ```PowerShell
  > Invoke-WebRequest -Uri https://winbootstrap.saltproject.io -OutFile C:\bootstrap-salt.ps1
  > C:\bootstrap-salt.ps1
  ```
- Execute `salt-call`:
  ```PowerShell
  > & 'C:\Program Files\Salt Project\Salt\salt-call.bat' --local test.ping
  [WARNING ] Failed to open log file, do you have permission to write to C:\ProgramData\Salt Project\Salt\var\log\salt\minion?
  local:
      True
  ``` 
I suspect this might be caused by the fact, that the script `bootstrap-salt.ps1` is full of harcoded paths pointing to `C:\salt`, whereas the new default path is now `${env:ProgramFiles}\Salt Project\Salt`.

### Versions and Systems
**Versions Report**:
```
    Salt Version:
              Salt: 3004

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: 3.1.18
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
      python-gnupg: 0.4.7
            PyYAML: 5.4.1
             PyZMQ: 19.0.0
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.2

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 10
            system: Windows
           version: 10 10.0.19041 SP0 Multiprocessor Free
```
