### ISSUE TITLE
Bootstrapping doesn't use Oracle's EPEL on Oracle Linux

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt-bootstrap#1838]
### Description of Issue/Question
salt-bootstrap installs the Fedora epel-latest repo (dl.fedoraproject.org/pub/epel/epel-release-latest-...) rather than using Oracle's EPEL repo on Oracle Linux.

I would expect it to install oracle-epel-release-el7 or oracle-epel-release-el8 package, which points to Oracle's repo.

PR to follow.

### Setup
Oracle Linux 8.6
Download and unzip https://github.com/saltstack/salt-bootstrap/archive/refs/heads/develop.zip

### Steps to Reproduce Issue
<details><summary>Excerpt from sh salt-bootstrap.sh -D</summary>

```
...
 *  INFO: Running install_oracle_linux_stable_deps()
warning: /var/tmp/rpm-tmp.ameQbW: Header V4 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
Verifying...                          ########################################
Preparing...                          ########################################
Updating / installing...
epel-release-8-15.el8                 ########################################
Cache was expired
17 files removed
Extra Packages for Enterprise Linux 8 - x86_64  2.4 MB/s |  11 MB     00:04    
Extra Packages for Enterprise Linux Modular 8 - 1.9 MB/s | 1.0 MB     00:00    
Oracle Linux 8 BaseOS Latest (x86_64)           6.1 MB/s |  46 MB     00:07    
Oracle Linux 8 Application Stream (x86_64)       12 MB/s |  36 MB     00:02    
SaltStack latest Release Channel for RHEL/CentO 1.3 MB/s | 245 kB     00:00    
Package yum-utils-4.0.21-11.0.1.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
...
```
</details>

### Versions and Systems
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.35-1-pve
        system: Linux
       version: Oracle Linux Server 8.6 
```
</details>

sh salt-bootstrap.sh -v
```yaml
salt-bootstrap.sh -- Version 2022.05.19
```
