### ISSUE TITLE
bootstrap-salt.sh.sha256 hash doesn't match actual

### ISSUE THREAD

**Issue by Hell-Fire** [saltstack/salt-bootstrap#1858]
https://github.com/saltstack/salt-bootstrap/commit/5511dff5a1310675e431d494068de8541bd5bf8c updated bootstrap-salt.sh without updating [bootstrap-salt.sh.sha256](https://github.com/saltstack/salt-bootstrap/blob/stable/bootstrap-salt.sh.sha256)

```
/tmp/bootstrap-salt.sh:
  file.managed:
  - source: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
  - source_hash: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh.sha256
  - mode: "0700"
```

```
          ID: /tmp/bootstrap-salt.sh
    Function: file.managed
      Result: False
     Comment: Specified sha256 checksum for /tmp/bootstrap-salt.sh (e92e1df6930285cf23eda188bee3cfa3dd6c577b4fb7aa91b29213ad820199b1) does not match actual checksum (50ce4b5f978b07f2fdad7350313fcc0a5ffe37df1bf3c89ba66951a578531bb3)
     Started: 16:58:29.401881
    Duration: 680.777 ms
     Changes:
```
