### ISSUE TITLE
Remote execution of bootstrap-salt.sh hangs with "git develop" args

### ISSUE THREAD

**Issue by abemusic** [saltstack/salt-bootstrap#193]
When running `salt-cloud -ldebug -m foo.map` to launch a new machine it hangs while executing the remote /tmp/deploy.sh on the minion. Here's the last bit of the log I have:

```
[INFO    ] Running command under pid 13071: "ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /home/ubuntu/projects/stackdio_root/stackdio/storage/cloud/aws-platform-account/id_rsa ubuntu@10.164.54.148 'sudo sh /tmp/deploy.sh -c /tmp/ -D git develop'"
[DEBUG   ] Executing command(PID 13071): 'sudo sh /tmp/deploy.sh -c /tmp/ -D git develop'
```

I have to load a new shell and manually kill the salt-cloud process to get keyboard access to the shell that ran salt-cloud. The profile I'm using:

```
ubuntu-1204:
  image: XXX
  provider: aws-platform-account
  script: bootstrap-salt
  script_args: -D git develop
  size: Large Instance
  ssh_username: ubuntu
```

Removing the "git develop" args fixes the issue and salt-cloud runs like normal. 

Also, I can run the remote SSH command manually and it works. Not sure if it's worth noting, but when I run it manually I get all the output from deploy.sh and it adds color to the different log levels it spits out. I'm wondering if it's some sort of TTY issue?
