### ISSUE TITLE
Salt Minion service not enabled by default on Fedora

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt-bootstrap#274]
I used Salt Cloud to spin up some Fedora instances. The Fedora minions spun up just fine and Salt worked great.

Once I restarted the virtual machine, the salt-minion service did not start up. I had to ssh in and start it manually.

Once I run `salt fedora_minion service.enable salt-minion` the minion service starts up at system boot just fine.

Here's the profile I'm using:

``` yaml
fedora_ec2:                                                                     
  provider: class-ec2                                                           
  image: ami-b22e5cdb                                                           
  size: Micro Instance                                                          
  ssh_username: fedora
```

This is causing issues with the Salt Training manual because we use some Fedora instances that get rebooted several times over the course of the training.
