### ISSUE TITLE
Hostname based on minion id

### ISSUE THREAD

**Issue by bastienk** [saltstack/salt-bootstrap#661]
Hello,

Would you be interested by a feature who changes the hostname based on the minion id in the bootstrap-salt.sh? If yes, I can do a pull request.

Thank you

**Comment by stardust85** [comment]
Hi, I would definitively love such feature! Please do it! :)

**Comment by s0undt3ch** [comment]
I can only say yes if its done for all the OS's that the script supports. Just adding support to one of the supported OS's will make someone else implement that same feature for the remaining distros. I don't currently have the time bandwidth to do it...

**Comment by s0undt3ch** [comment]
Also, once the minion is up, salt can better do that for us...

**Comment by stardust85** [comment]
Makes sense. I forgot that I can do it in the state.

**Comment by vutny** [comment]
Very generic SLS for doing this:

```
set-hostname:
  file.managed:
    - name: /etc/hostname
    # hostname is always minion ID.
    - contents_grains: id
    - user: root
    - group: root
    - mode: 644
  cmd.wait:
    # Will fail in Docker container.
    # Use `docker run --hostname=hostname' command to spin up.
    - name: hostname -F /etc/hostname || true
    - watch:
      - file: set-hostname

{%- if grains['os_family'] == 'RedHat' %}

/etc/sysconfig/network:
  file.replace:
    - name: /etc/sysconfig/network
    - pattern: ^.*HOSTNAME=.*
    - repl: HOSTNAME="{{ grains['id'] }}"
    - append_if_not_found: True

{%- endif %}
```
