### ISSUE TITLE
Salt-cloud config options not being passed by salt-bootstrap

### ISSUE THREAD

**Issue by beardedeagle** [saltstack/salt-bootstrap#776]
## Description of Issue/Question

When using the latest `bootstrap-salt.sh` it does not honor config options passed via salt-cloud, at least for _**Openstack**_. This is only broken within the last couple of months.
## Setup

Example /etc/salt/cloud.provider.d/base-provider.conf (vastly shortened):

```
...
base-provider:
  driver: openstack
  compute_name: nova
  service_type: compute
  protocol: ipv4
  ssh_interface: private_ips

  ssh_key_name: <REDACTED>
  ssh_key_file: /home/<REDACTED>/.ssh/id_rsa
  wait_for_passwd_maxtries: 3000
  ssh_username: root

  user: <REDACTED>
  password: <REDACTED>

  delete_sshkeys: True
  sync_after_install: all
  start_action: state.highstate
  display_ssh_output: False
  cache_event_strip_fields:
    - password
    - priv_key

phx3dev-playground:
  extends: base-provider:openstack
  identity_url: <REDACTED>
  compute_region: phx3
  tenant: phx3dev-playground
...
```

Example /etc/salt/cloud.profile.d/base-profile.conf (vastly shortened as the file has 2485 lines):

```
...
base-cent6-minion-phx3:
  provider: phx3prod-playground
  image: 'centos67-base-20160308a-0.0.7-1.el6'
  security_groups: default
  script: bootstrap_salt.sh
  script_args: -Z
  minion:
    master: <REDACTED>
    append_domain: cloud.dev.phx3.gdg
    mine_interval: 10
    multiprocessing: True
  userdata_file: /etc/salt/cloud.deploy.d/userdata.yml
  grains:
    role: minion

base-cent6-syndic-phx3:
  provider: phx3prod-playground
  image: 'centos67-base-20160308a-0.0.7-1.el6'
  security_groups: default,Salt
  script: bootstrap_salt.sh
  script_args: -MSFZ -p salt-cloud -p salt-api
  make_master: True
  master:
    interface: 0.0.0.0
    worker_threads: 10
    external_auth:
      pam:
        <REDACTED>:
          - .*
          - '@runner'
          - '@wheel'
          - '@jobs'
    file_roots:
      base:
        - /srv/salt
      dev:
        - /srv/dev/salt
      test:
        - /srv/test/salt
      ote:
        - /srv/ote/salt
      prod:
        - /srv/prod/salt
    env_order: ['base', 'dev', 'test', 'ote', 'prod']
    pillar_roots:
      base:
        - /srv/pillar
      dev:
        - /srv/dev/pillar
      test:
        - /srv/test/pillar
      ote:
        - /srv/ote/pillar
      prod:
        - /srv/prod/pillar
    syndic_master: <REDACTED>
  minion:
    master: <REDACTED>
    append_domain: cloud.dev.phx3.gdg
    mine_interval: 10
    multiprocessing: True
  userdata_file: /etc/salt/cloud.deploy.d/userdata.yml
  file_map:
    /etc/salt/cloud.deploy.d/base-map.map: /etc/salt/cloud.maps.d/base-map.map
    /etc/salt/cloud.deploy.d/base-profile.conf: /etc/salt/cloud.profiles.d/base-profile.conf
    /etc/salt/cloud.deploy.d/base-provider.conf: /etc/salt/cloud.providers.d/base-provider.conf
    /etc/salt/cloud.deploy.d/bootstrap_salt.sh: /etc/salt/cloud.deploy.d/bootstrap_salt.sh
    /etc/salt/cloud.deploy.d/bootstrap_salt.ps1: /etc/salt/cloud.deploy.d/bootstrap_salt.ps1
    /etc/salt/cloud.deploy.d/reactor.conf: /etc/salt/master.d/reactor.conf
    /etc/salt/cloud.deploy.d/salt-api.conf: /etc/salt/master.d/salt-api.conf
    /etc/salt/cloud.deploy.d/Salt-Minion-2015.8.7-AMD64-Setup.exe: /etc/salt/cloud.deploy.d/Salt-Minion-2015.8.7-AMD64-Setup.exe
    /etc/salt/cloud.deploy.d/userdata.ps1: /etc/salt/cloud.deploy.d/userdata.ps1
    /etc/salt/cloud.deploy.d/userdata.yml: /etc/salt/cloud.deploy.d/userdata.yml
    /etc/salt/cloud.deploy.d/winexe-1.1-b787d2.el6.x86_64.rpm: /etc/salt/cloud.deploy.d/winexe-1.1-b787d2.el6.x86_64.rpm
    /etc/salt/cloud.deploy.d/winexe-1.1-b787d2.el7.centos.x86_64.rpm: /etc/salt/cloud.deploy.d/winexe-1.1-b787d2.el7.centos.x86_64.rpm

minion-phx3-gen-zone-1-tiny_cent6:
  extends: base-cent6-minion-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.tiny

minion-phx3-gen-zone-1-small_cent6:
  extends: base-cent6-minion-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.small

minion-phx3-gen-zone-1-medium_cent6:
  extends: base-cent6-minion-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.medium

minion-phx3-gen-zone-1-large_cent6:
  extends: base-cent6-minion-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.large

minion-phx3-gen-zone-1-xlarge_cent6:
  extends: base-cent6-minion-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.xlarge

syndic-phx3-gen-zone-1-tiny_cent6:
  extends: base-cent6-syndic-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.tiny

syndic-phx3-gen-zone-1-small_cent6:
  extends: base-cent6-syndic-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.small

syndic-phx3-gen-zone-1-medium_cent6:
  extends: base-cent6-syndic-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.medium

syndic-phx3-gen-zone-1-large_cent6:
  extends: base-cent6-syndic-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.large

syndic-phx3-gen-zone-1-xlarge_cent6:
  extends: base-cent6-syndic-phx3
  availability_zone: phx-private-gen-zone-1
  size: m1.xlarge
...
```
## Steps to Reproduce Issue

1.) Install and set up salt-master
2.) Install and set up salt-cloud
3.) Provision a minion or syndic with salt-cloud with config options in your cloud/map/profile/provider
## Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.7

Dependency Versions:
 Apache Libcloud: 0.20.0
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
            Mako: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.7.0
          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
            cffi: 0.8.6
        cherrypy: 3.2.2
        dateutil: 1.5
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
         libgit2: 0.21.0
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: 0.21.4
    python-gnupg: Not Installed
           smmap: Not Installed
         timelib: Not Installed

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.10.1.el7.x86_64
          system: CentOS Linux 7.2.1511 Core
```

**Comment by rallytime** [comment]
Hi @beardedeagle - I believe this may have been a bug in salt-cloud itself. I am curious if you're still running into this issue. I tried a simple test case with just adding some minion configs like so:

```
root@rallytime:~# cat /etc/salt/cloud.profiles.d/linode.conf
base:
  provider: linode-config
  size: Linode 2048
  script_args: 'git 2016.3'
linode-centos-7:
  extends: base
  image: CentOS 7
  minion:
    foo: bar
    hello: world
```

And then provisioned the VM via salt-cloud:

```
root@rallytime:~# salt-cloud -p linode-centos-7 rally-test-776
```

And checked the contents of the minion file:

```
root@rallytime:~# salt rally-test-776 cmd.run 'cat /etc/salt/minion'
rally-test-776:
    foo: bar
    hash_type: sha256
    hello: world
    id: rally-test-776
    log_level: info
    master: <redacted>
```

And everything looks as I expect it to. My master is on 2016.3.1.

Can you let us know if you're still running into a problem here using a newer version of Salt? If the problem persists, I think it might make more sense for this issue to be opened against the salt repo itself, with some more details of what information is missing and where.

As this issue stands, I am not sure if it is master configs that are not getting propagated the way you think they should, minion configs, grains, etc. You've got a lot of settings in there and I want to make sure this is working properly for you.
