### ISSUE TITLE
SL 6.x bootstrap and yum repo install issues

### ISSUE THREAD

**Issue by kmkramer** [saltstack/salt-bootstrap#833]
on SL 6.x $releasever returns both the major and minor strings for the release, whereas SL 7.2 returns just the major version. this borks salt from being installed.
this will return yum VARS: python -c 'import yum, pprint; yb = yum.YumBase();  \ pprint.pprint(yb.conf.yumvar, width=1)'

``` yaml
sl6.5 host
'releasever': '6.5',

salt grains
osmajorrelease:
        6
    osrelease:
        6.5
    osrelease_info:
        - 6
        - 5

sl7.2 host

'releasever': '7'

salt grains
osmajorrelease:
        7
    osrelease:
        7.2
    osrelease_info:
        - 7
        - 2
```

basically SL6 and SL7 differ in how they report the DISTRO\* vars
