### ISSUE TITLE
python-requests obsolete on Fedora

### ISSUE THREAD

**Issue by mauved** [saltstack/salt-bootstrap#875]
### Description of Issue/Question

Running the bootstrap script fails on a fresh Fedora 23 installation since it looks like the package `python-requests` was split up into `python2-requests` and `python3-requests`.

```
Last metadata expiration check: 0:12:21 ago on Thu Jun 16 22:25:35 2016.
Package PyYAML-3.11-11.fc23.x86_64 is already installed, skipping.
Package libyaml-0.1.6-7.fc23.x86_64 is already installed, skipping.
Package python-crypto-2.6.1-7.fc23.x86_64 is already installed, skipping.
Error: installed package python2-requests-2.10.0-2.fc23.noarch obsoletes python-requests < 2.10.0-2.fc23 provided by python-requests-2.7.0-7.fc23.noarch
(try to add '--allowerasing' to command line to replace conflicting packages)
 * ERROR: Failed to run install_fedora_deps()!!!
```

I was able to get Salt bootstrapped on this system my modifying line 3176 and replacing `python-requests` with `python2-requests`.
### Versions and Systems

```
[root@salty ~]# ./bootstrap-salt.sh -v
./bootstrap-salt.sh -- Version 2016.05.11
[root@salty ~]# cat /etc/fedora-release 
Fedora release 23 (Twenty Three)
```

**Comment by jfindlay** [comment]
@mauved, thanks for reporting.

**Comment by rallytime** [comment]
@mauved Can you tell me how you're running the bootstrap script? (Any other options you're passing in?) I just ran the bootstrap script a couple of times on two Fedora 23 boxes and I am having trouble reproducing this error. I ran it first without any options, and then I ran it to install via git (`sh install_salt.sh -P git v2016.3.1`).

Here's my information from the last run:

```
[root@fedora ~]# sh install_salt.sh -v
install_salt.sh -- Version 2016.06.27
[root@fedora ~]# cat /etc/fedora-release
Fedora release 23 (Twenty Three)
[root@fedora ~]# salt-call --local test.versions_report
local:
    Salt Version:
               Salt: 2016.3.1

    Dependency Versions:
               cffi: 1.4.2
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.11 (default, Mar 31 2016, 20:46:51)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist: fedora 23 Twenty Three
            machine: x86_64
            release: 4.5.5-x86_64-linode69
             system: Linux
            version: Fedora 23 Twenty Three
```
